### ISSUE TITLE
Tabs line colors

### ISSUE THREAD

**Issue by elig0n** [miconda/lucariox.vim#1]
Hi,
The tabs line look out of touch with the rest of the color.
Why is it so ?

**Comment by miconda** [comment]
Hello, I don't think I touched those settings, so likely it comes from Lucario. It seems to be like cyan on grey. What you would suggest to fit better? Thanks.

**Comment by elig0n** [comment]
well, I currently put these instead:

" Colors for tabs in cterm
hi TabLineFill  ctermfg=60
hi TabLine      ctermfg=white ctermbg=60 cterm=NONE
hi TabLineSel   ctermfg=white ctermbg=61 cterm=NONE

Though, I would suggest something else for the selected tab bg/fg. Something a little more blending.

**Comment by miconda** [comment]
For now I pushed yours with 254 instead of white, I am not much into using tabs, but just buffers. Will try to play with other options once I get some more spare time. Thanks!
